repos:
- repo: local
  hooks:
  - id: formatter
    name: Format license configuration files
    entry: ./licenseSorter.py
    language: python
    verbose: true
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3.8
      verbose: true
