#!/usr/bin/env bash

# Each test consists of a project directory containing:
# - project: The necessary project files including the THIRD-PARTY.txt files.
# - expected: The expected csv file(s).
# - command.sh: The command to launch the CSV creator script.
# - (actual): A folder that will be generated by this test containing the actual generated csv file(s).

SCRIPT_DIR=`dirname "$0"`

errors="false"
for project in `ls "$SCRIPT_DIR/projects"`
do
    echo "Running test against $project"
    rm -rf $SCRIPT_DIR/projects/$project/actual
    $SCRIPT_DIR/projects/$project/command.sh "$SCRIPT_DIR/../../thirdPartyLicenseCSVCreator.py"
    diff -r $SCRIPT_DIR/projects/$project/expected $SCRIPT_DIR/projects/$project/actual
    if [[ $? == 0 ]]
    then
        echo -e "Passed!\n"
    else
        echo -e "Failed!\n"
        errors="true"
    fi
done

if [[ $errors == "true" ]]
then
    echo "There were e2e test failures."
    exit 1
else
    echo "All e2e tests passed."
fi
