name: Third-party License Overrides CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  pre_commit:
    name: "pre-commit"
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/automate-build-tools/.github/actions/pre-checks@cbeee1dd8bcf96fa926dcd6fe0445220ba6afe07 # v0.10.0

  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    needs: [ pre_commit ]
    steps:
      - uses: actions/checkout@v4
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@8cd8c3798c79d10540e2876ad7cf2a5311cbd1ae # v8.20.0
      - name: "Compile"
        run: |
          cd test
          javac -d target ./org/alfresco/thirdpartylicense/ValidateProperties.java
      - name: "Run tests"
        run: |
          cd test
          echo -e "\n~~~ Unit tests ~~~\n"
          java -cp target org.alfresco.thirdpartylicense.ValidateProperties
          echo -e "\n~~~ Script E2E tests ~~~\n"
          ./thirdPartyLicenseCSVCreatorTests/test.sh
          echo -e "\n~~~ Plugin E2E tests ~~~\n"
          cd pluginE2ETests
          mvn clean install